# Site settings
title: Ethan Blog
email: zhjuncai@outlook.com
description: My Personal Blog, recording my learning path, and sharing what I had learned 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zhjuncai
github_username:  zhjuncai

# Build settings
markdown: kramdown
