# Site settings
title: Bazinga
email: zhjuncai@outlook.com
description: Learning Swift, keep swifty 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zhjuncai
github_username:  zhjuncai

# Build settings
markdown: kramdown
